#!/bin/sh

browserify -t [ babelify --presets [ react ] ] \
           -o bundle.js                        \
           -r ./app.js:app                     \
           ./app.js                            \
&& open index.html
