#!/bin/sh

browserify -t [ babelify --presets [ react ] ] \
           -o bundle.js                        \
           -r ./renderers:renderers            \
           ./renderers.js                      \
&& open index.html
